apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  # annotations:
  #   volume.beta.kubernetes.io/storage-class: "ibmc-file-silver"
  labels:
    app: hello-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi