apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: hello-postgresql
spec:
  selector:
    app: hello-postgresql
    tier: postgreSQL
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  # loadBalancerSourceRanges:
  #  - 127.0.0.1/32